<?php
 foreach ($this->getScripts() as $script):
?>
     <script>
         let scriptElm = document.createElement('script');
         scriptElm.src = '<?php echo $script; ?>';
         document.head.appendChild(scriptElm);
     </script>
<?php endforeach;?>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div id="integrai-payment"></div>
</div>