<?php
$additionalInformation = $this->getPaymentResponse();

if(!empty($additionalInformation)):
?>
    <?php if(!empty($additionalInformation['module_name'])): ?>
        <div>
            <strong>Processado por: </strong> <?php echo $additionalInformation['module_name']; ?>
        </div>
    <?php endif; ?>

    <?php if(!empty($additionalInformation['transaction_id'])): ?>
        <div>
            <strong>Identificação da transação: </strong> <?php echo $additionalInformation['transaction_id']; ?>
        </div>
    <?php endif; ?>

    <?php if(!empty($additionalInformation['date_approved'])): ?>
        <div>
            <strong>Data de pagamento: </strong> <?php echo $additionalInformation['date_approved']; ?>
        </div>
    <?php endif; ?>

    <?php if(!empty($additionalInformation['payment_method'])): ?>
        <?php if($additionalInformation['payment_method'] === 'pix' && !empty($additionalInformation['qr_code_base64']) && !empty($additionalInformation['qr_code'])): ?>
            <div style="margin-top: 1rem">
                <img height="150" style="height: 150px" src="data:image/jpeg;base64,<?php echo $additionalInformation['qr_code_base64']; ?>"/>
                <div>
                    <strong>Código QR: </strong>
                </div>
                <input style="width: 80%;padding: .5rem;" readonly value="<?php echo $additionalInformation['qr_code']; ?>">
            </div>
        <?php endif; ?>

        <?php if($additionalInformation['payment_method'] === 'boleto' && !empty($additionalInformation['boleto_url'])): ?>
            <div style="margin-top: 1rem">
                <button title="Imprimir boleto" type="button" class="scalable go" onclick="setLocation('<?php echo $additionalInformation['boleto_url']; ?>')">
                        <span>
                            <span>
                                <span>Imprimir boleto</span>
                            </span>
                        </span>
                </button>
            </div>
        <?php endif; ?>

        <?php if($additionalInformation['payment_method'] === 'credit_card' && isset($additionalInformation['card'])): ?>
            <div style="margin: 0.5em 0;">
                <h3>Dados do cartão de crédito</h3>
                <?php if(!empty($additionalInformation['installments'])): ?>
                <div>
                    <strong>Parcelas: </strong> <?php echo $additionalInformation['installments']; ?>
                </div>
                <?php endif; ?>

                <?php if(!empty($additionalInformation['card']['last_four_digits'])): ?>
                <div>
                    <strong>Número do cartão: </strong> **** **** **** <?php echo $additionalInformation['card']['last_four_digits']; ?>
                </div>
                <?php endif; ?>

                <?php if(!empty($additionalInformation['card']['holder'])): ?>
                <div>
                    <strong>Nome do titular: </strong> <?php echo $additionalInformation['card']['holder']; ?>
                </div>
                <?php endif; ?>

                <?php if(!empty($additionalInformation['card']['expiration_month']) && !empty($additionalInformation['card']['expiration_year'])): ?>
                <div>
                    <strong>Data de expiração: </strong> <?php echo $additionalInformation['card']['expiration_month']; ?> / <?php echo $additionalInformation['card']['expiration_year']; ?>
                </div>
                <?php endif; ?>

                <?php if(!empty($additionalInformation['card']['brand'])): ?>
                <div>
                    <strong>Bandeira: </strong> <?php echo strtoupper($additionalInformation['card']['brand']); ?>
                </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
