<?php
$additionalInformation = $this->getPaymentResponse();

if(!empty($additionalInformation)):
    $marketplace_data = $additionalInformation['marketplace_data'];
    $payments = $additionalInformation['payments'];
?>
    <?php if(count($marketplace_data) > 0): ?>
        <h4>Dados marketplace</h4>
        <p>
            <?php
            foreach ($marketplace_data as $key => $value) {
                if (!empty($value)) {
                    echo '<div><strong>' . $key . ':</strong> ' . $value . '</div>';
                }
            }
            ?>
        </p>
        <hr />
    <?php endif; ?>

    <?php if(count($payments) > 0): ?>
        <p>
        <?php foreach ($payments as $index => $payment_data):?>
            <?php
            if(count($payments) > 1) {
                echo '<strong>' . ($index + 1) . 'º forma de pagamento</strong>';
            }
            ?>

            <p>
            <?php foreach ($payment_data as $key => $value): ?>
                <?php if(!empty($value) && !is_object($value) && !is_array($value)): ?>
                    <div><strong><?php echo $key ?></strong> <?php echo $value; ?></div>
                <?php endif; ?>

                <?php if($key == 'boleto' && is_array($value) && !empty($value['url'])): ?>
                    <div style="margin-top: 1rem">
                        <button title="Imprimir boleto" type="button" class="scalable go" onclick="setLocation('<?php echo $value['url']; ?>')">
                            <span>
                                <span>
                                    <span>Imprimir boleto</span>
                                </span>
                            </span>
                        </button>
                    </div>
                <?php endif; ?>

                <?php if($key == 'pix' && is_array($value)): ?>
                    <div style="margin-top: 1rem">
                    <?php if(!empty($value['qr_code_base64']) || !empty($value['qr_code_image'])): ?>
                        <img
                            height="150"
                            style="height: 150px"
                            src="<?php echo isset($value['qr_code_base64']) ? 'data:image/jpeg;base64,' . $value['qr_code_base64'] : $value['qr_code_image']; ?>"/>
                    <?php endif; ?>
                    <?php if(!empty($value['qr_code'])): ?>
                        <div>
                            <strong>Código QR: </strong>
                        </div>
                        <input style="width: 80%;padding: .5rem;" readonly value="<?php echo $value['qr_code']; ?>">
                    <?php endif; ?>
                    </div>
                <?php endif; ?>

                <?php
                if ($key == 'card' && is_array($value)) {
                    foreach ($value as $cardKey => $cardValue) {
                        if (!empty($cardValue)) {
                            echo '<div><strong>' . $cardKey . ':</strong> ' . $cardValue . '</div>';
                        }
                    }
                }
                ?>
            <?php endforeach; ?>
            </p>
        <?php endforeach; ?>
        </p>
    <?php endif; ?>
<?php endif; ?>
